name: Label PR

on:
  pull_request:

jobs:
  label:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Assign labels based on target branch
        uses: shiftEscape/auto-label-pulls@main
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          config-path: ".github/config/branch-labels.json"
